# Generated by Django 2.2.4 on 2019-08-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=True, verbose_name='Markdown语法'),
        ),
    ]
