# Generated by Django 2.2.3 on 2019-08-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190820_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-weight'], 'verbose_name': '友链', 'verbose_name_plural': '友链'},
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最新文章'), (3, '最热文章'), (4, '最近评论'), (5, '友情链接')], default=1, verbose_name='展示类型'),
        ),
    ]
