# Generated by Django 2.2.4 on 2019-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20190826_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.TextField(blank=True, help_text='如果设置的不是HTML类型，可为空', verbose_name='内容'),
        ),
    ]
